### PR TITLE
.NET Standard support

### PR DESCRIPTION
**Pull request by igitur**
This PR adds support for `netstandard2.0`. I still have to add the `.transform` files to the nuspec, but please let met know if you're OK with the general direction of this PR.

Would you also mind adding one of the standard open source licenses, e.g. MIT ?

### CODE REVIEW

**Comment by igitur** [comment]
@doug-l-mitchell If you don't want to support this library anymore, I'll happily take it off you. I already maintain other libraries. You can check out the Nuget packages under my control at https://www.nuget.org/profiles/igitur

But, please man, at least reply.

**Comment by doug-l-mitchell** [comment]
Hi @igitur. It seems that I missed the earlier messages. As you can tell by the last release date of the nuget package, this isn't something I've been actively supporting. I'll be happy to hand this off to you as I see that you are doing much good in the open source community. What do you need from me to make this happen?

**Comment by igitur** [comment]
Thanks for getting back to me. I suggest leaving the repo here under your account, if you're OK with that. Then add me as a collaborator under https://github.com/doug-l-mitchell/ObjectCacheExtension/settings/access . And add me as an owner on the Nuget package page.

**Comment by igitur** [comment]
Thanks for the repository access. If you can just give me Nuget package access as well, then I can take this further.

**Comment by doug-l-mitchell** [comment]
Apologies for the delay. I was not able to log in and lost track of this
while waiting to get that resolved. I've added you as an owner in Nuget.

Thanks again for all the work you're doing in the OSS community.

Doug

**Comment by igitur** [comment]
Thanks, all sorted now. I'll take it from here. After the 2 PRs, there's hopefully not much else to do here.

**Comment by igitur** [comment]
Oh, about the licensing, are you OK with licensing this under MIT?

**Comment by doug-l-mitchell** [comment]
That's fine with me.

**Pull request merged**
